### ISSUE TITLE
Numeric Search produces sql error

### ISSUE THREAD

**Issue by jasonbrennan** [Octopoos/SEBLOD#102]
## Expected Behavior ##
User should be able to search for a numeric string and receive usable results. 

## Actual Results ##
If the user searches fro a numeric string that contains part of a Seblod CCK_id they receive the error below.
SQL Error : .....  `WHERE a.id = "5<span class="highlight">405</span>";`

In my case the problem results are with the returned Seblod categories that contain a matching Seblod CCK_id. 

While I would prefer to just remove those specific results, maybe there is an edge case and it isn't the desired behavior for everyone? The returned category content doesn't actually match what the user is looking for but rather an Seblod CCK id that is only used behind the scenes.

## Steps To Reproduce ##
* Create multiple Seblod categories 
  * For testing locate the cck id in the article text in our example it is 5405 `::cck::5405::/cck::`
* Create multiple Seblod items with numeric titles
  * Use parts of the category id 405 or 540 would work
* Search for one of the numeric titles using the Joomla default Search

## Cause ##

Joomla is running the search and then modifying the result string prior to running the onContentPrepair plugins. So when the Seblod _prepare method gets the content it has been modified like the object below and seblod is running a sql query with HTML. `plugins/content/cck/cck.php:165`

    stdClass Object
    (
        [title] => PreTest
        [text] => ::cck::5<span class="highlight">405</span>::/cck:: ::description::PreTest::/description::&#160;...
        [created] => 
        [browsernav] => 2
        [catid] => 127
        [slug] => 127:pretest
        [href] => index.php?option=com_content&view=category&id=127&Itemid=39
        [section] => Category
    )

## Possible Solution ##
The modified code below has worked as a temporary solution for my needs and is only here to help illustrate the problem I was having and may not be the best overall solution.

    $search = str_replace(['<span class="highlight">','</span>'],'',$article->$property);
    preg_match( '#::cck::(.*)::/cck::#U', $search, $matches );

**Comment by Octopoos-James** [comment]
Hi Jason,

Thanks for reporting this, I'm sure someone with more knowledge than me will directly address the technical details of this - but can I ask why you're using the Joomla Search instead of building your search functionality with SEBLOD?

Ideally, you should use the SEBLOD Search Generic and construct a global site search using SEBLOD natively, not Joomla. Even if this issue was fixed, you will still have the problems that one encounters when using the Joomla site search and SEBLOD with the router and URLS not playing nicely. This often results in sub-optimal SEO due to 'duplicate content.'

I would avoid using the Joomla Search component and build your required search functionality with SEBLOD.

Cheers,
James

**Comment by jasonbrennan** [comment]
James, 

Thank you for the information. I know there were some issues getting the Seblod search working. It may have been more of a knowledge issue than a technical one though. I will check on that and then see how it impacts the original issue.

Jason

**Comment by sebastienheraud** [comment]
Hi all,
Fix is here: https://github.com/Octopoos/SEBLOD/commit/3b5e3119ec6a169b893f8d3686b4f9034111a8e8
Thanks,
Saba.
