### ISSUE TITLE
reply-to attribute in email field

### ISSUE THREAD

**Issue by etnr** [Octopoos/SEBLOD#404]
Unfortunately the "From" attribute does not work in my webhoster because does only send mails if the "from" email adress is known / set up on the server itself. A "reply-to" would work and would be the "correct" setup.
Tkz

**Comment by paoprod** [comment]
Most of Web Hoster (Siteground in my case) ask for same domain for the website hosting the form AND on "From" field for email sent by that form (mail sent by PHP mail in configuration). So Yes, I agree, a "Reply-to" field on the Email Seblod plugin is today a real requirement. Any chance to see that one day ?

**Comment by svenlewerentz** [comment]
Hello, is there any chance a "reply to" option will be added? I need it for multiple projects and my client is really annoyed that he can't simply reply to emails submitted by the form.

**Comment by sebastienlapoux** [comment]
Hi @etnr , @paoprod , @svenlewerentz ,
yes, you're right.
Since some time any email sent from a site must use for the from an email@yoursitedomainname (related to the authentification of the sender, DKIM, SPF...)

That said, we can no more push into the from the email that we wish for the answer.

The good solution is the reply-to.

Currently in development, we're trying to push this into the next version.

Thanks!

**Comment by sebastienlapoux** [comment]
Included into next version.

**Comment by Giuse69** [comment]
I think it can be closed since implemented in 3.16

**Comment by sebastienlapoux** [comment]
Yes :-).
Thanks @Giuse69 !
