### ISSUE TITLE
1064 - You have an error in your SQL syntax in Select Dynamic Cascade

### ISSUE THREAD

**Issue by Andre72** [Octopoos/SEBLOD#47]
When I'm using free SQL inside the Select Dynamic Cascade I get an exeption when I save the form:
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 14 SQL=SELECT article.id AS value, article.title AS text, parent_id FROM p2vcj_content AS article, ( SELECT id, related_nationality AS parent_id FROM xxxxx_cck_store_form_dn_series ) AS related, ( SELECT id, title FROM p2vcj_content WHERE catid =30 ) AS series WHERE article.id = related.id AND parent_id = series.id AND parent_id =#parent_id# order by text

As you can see  parent_id =#parent_id# - placeholder is not replaced

The error occurs in function protected static function _getOptionsList, line 601 of the lattest version as query can nt be executed because of placeholder in query.
Same happens if I try [parent] as shown in replace:
preg_replace( '/('.$opt_parent.' ?= ?\[parent\]|'.$opt_parent.' ?= ?\#parent_id\#)/', $opt_value.' = "'.$value.'"', $opt_query );

**Comment by lionelratel** [comment]
Hello Andre72,
I just tested the Plugin Field Select Dynamic Cascade and don't find any thing wrong when using this plugin in the FREE mode.
I think that your problem it's more due to your request which generate the 1064 error.
It don't really understand what you try to do with this query. 
I would advise to just use 2 variables in the SELECT for text and value, and add some LEFT JOIN to restrict your data.
I wrote a tutorial on "How To" use this plugin in free mode : http://www.seblod.com/resources/tutorials/how-to-use-select-cascade-with-free-queries

Regards.
Lionel

**Comment by olivier-at-octopoos** [comment]
Hi Andre72,

Have you had a chance to check what Lionel mentioned ?

As this issue is opened for more than 1 month and without feedback from you, we plan to close it in the coming days.

Thanks,
Olivier

**Comment by Andre72** [comment]
Hi Olivier,

 

es Lionel is right – it’s not a bug but my mistake.

 

Best regards

Andre

 

Von: Olivier Nolbert [mailto:notifications@github.com] 
Gesendet: Mittwoch, 17. Juni 2015 15:02
An: Octopoos/SEBLOD
Cc: Andre72
Betreff: Re: [SEBLOD] 1064 - You have an error in your SQL syntax in Select Dynamic Cascade (#47)

 

Hi Andre72,

Have you had a chance to check what Lionel mentioned ?

As this issue is opened for more than 1 month and without feedback from you, we plan to close it in the coming days.

Thanks,
Olivier

**Comment by sebastienheraud** [comment]
Report closed.
Thanks,
Saba.
