### ISSUE TITLE
Search on calendar field

### ISSUE THREAD

**Issue by lepache** [Octopoos/SEBLOD#474]
Hi,
I would like to get a list of name based on "date of death" calendar field.
Format field is d-m-Y
Storage format : Date time
Show Time : No
Default H M S : 00:00:00

In my datebase, the stored field is e.g 1942-11-08 00:00:00

So when I search a list with 08-11-1942 date of death, I have 0 result. The debug shows : AND t1.date_of_death = '1942-11-08 10:14:38'

The matching operator with button 3 is Exact, so it is normal that there is 0 result, because of time.

My question is : could somebody tell me why I have the current time (10:14:38) and not the default time (00:00:00) of the field option ? How to solve that ?

Thanks a lot

**Comment by klas** [comment]
This is not a Seblod bug - it is default behaviour of DateTime::createFromFormat to use current system time for he missing parts of datetime when you allow manual input:

http://php.net/manual/en/datetime.createfromformat.php

According to this you can use ! in the format to tell it to use UNIX epoch parts instead (so 00:00:00 in your case), but I'm not sure if javascript part of the calendar can handle it.

Otherwise just disable manual input and default time will be used.

**Comment by sebastienheraud** [comment]
Hi,

After a quick try, I'm not able to confirm the issue. It works as expected (without 00:00:00) when the related parameter is enabled on "JForm Calendar" field.
I would suggest to switch to this plug-in, even though it seems to be okay with the Calendar one.

Please use our forums if you need more help.

Thanks,
Saba.
