### ISSUE TITLE
Edit link isn't shown if only "edit own" permissions are applied on Content Type

### ISSUE THREAD

**Issue by Octopoos-James** [Octopoos/SEBLOD#63]
A SEBLOD edit link is not rendered for the user if their user group only has "edit own" permissions for that content type. The edit link is only rendered if the user has at least "edit" permissions.

Tested on SEBLOD 3.6.2 - Joomla 3.4.1

**Comment by Octopoos-James** [comment]
On further investigation of this, it seems to be an issue with the ordering of where the edit content link is placed within the view.

I've added an icon edit field with the link "Content > Edit" as the first field in the Mainbody position of seb_minima with all other fields after it, and the field wasn't rendered. However, if I placed the field second or last in the Mainbody position, it was rendered.

This seems to be a bug to me and should be looked at.

**Comment by sebastienheraud** [comment]
Hi James,
Indeed "putting one field from the object" at the first place (or at least before the link/permissions check) was the correct behaviour...
We've spent some time on it with Olivier, in order to implement a workaround/improvement to prevent the error even if the edit link/permissions check is in the first place.
This will be available in the next major release.
Regards,
Saba.
