### ISSUE TITLE
Select Dynamic Cascade - there is no Behavior field in the editor , joomla 4

### ISSUE THREAD

**Issue by step-di** [Octopoos/SEBLOD#658]
for Joomla 4.2 and 1.7.0 Select Dynamic Cascade - the Behavior field (select option Start, In Between or End) is not available
for php 7.4, php 8.0, php 8.1

**Comment by sebastienheraud** [comment]
Hi @step-di,

Thanks for reporting.
The regression should be fixed with 1.7.1.

An additional fix is included for PHP 8.x on both 1.7.1 (SEBLOD 4), and 1.6.2 (SEBLOD 3):

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/1101317/193318005-39a7249e-d038-445a-a54a-2ad499e1a276.png">

Saba
