### ISSUE TITLE
Entering a Message for the Site Form Has Hidden Character Limit

### ISSUE THREAD

**Issue by Octopoos-James** [Octopoos/SEBLOD#68]
The Message (thanks) Textarea (to display a message when a Site Form has been successfully saved) in the admin backend of SEBLOD Content Types has a character limit of 258 characters, but the validation warning on the field is not displayed if the user enters too much text. Instead, the console just notes an error: Uncaught TypeError: Cannot read property 'alertText' of undefined.

This is confusing for a user because it is not clear why they cannot save their Message (thanks) text which is longer than 258 characters.

**Comment by sebastienheraud** [comment]
Hey James,
Javascript error fixed in upcoming SEBLOD 3.8 release.
The validation plug-in will properly alert the maxlength now.
And by default, it will be 512 characters for all new install (starting with SEBLOD 3.8)
("core_message" dev field can already be edited for all existing sites)
Thanks,
Saba.
