### ISSUE TITLE
Seblod 4, Joomla 5 and com_search

### ISSUE THREAD

**Issue by webmasterpaca** [Octopoos/SEBLOD#813]
Hi,
Com_search is no longer available with Joomla 5. It is recommended to use com_finder instead.
With Joomla 4.4.1 and Seblod 4.3.1, so I tried to disable extensions "plg_search_cck" from the search directory. Seblod has stopped working.
Shouldn't we replace the "plg_search_cck" extension in the "search" directory with a "plg_finder_cck" extension installed in the finder directory?
Thanks

**Comment by sebastienheraud** [comment]
Hi @webmasterpaca,

You should not disable the "plg_search_cck" it is required to use all SEBLOD List & Search features.
It is not really related to com_search.

Without a "plg_finder_cck" plug-in you are already able to search for content items (i.e a custom WYSIWYG field), if you enable the following plug-in (Joomla! Content Article Object)

<img width="921" alt="image" src="https://github.com/Octopoos/SEBLOD/assets/1101317/bd0c4b88-2ed1-4a57-90b2-cc0cfa4f924f">

and you define from which view (Content or Intro) the content should be indexed, from your Content Type (using a Joomla! Article object)

<img width="731" alt="image" src="https://github.com/Octopoos/SEBLOD/assets/1101317/4c7ab62f-23d8-42cb-9463-2839bd2ca6e3">

and then you need to Index the content via:

<img width="820" alt="image" src="https://github.com/Octopoos/SEBLOD/assets/1101317/e34dd223-337c-4578-a3e8-92b1d0207330">

It would find and output results (using the Joomla! Smart Search view) which is not easy to custom o extend.
Is there any reason and requirement for you to use the Joomla! Smart Search component instead of SEBLOD List & Search capabilities?

Thanks,
Sebastien

**Comment by webmasterpaca** [comment]
Good morning,
There is no particular reason for me to use Joomla's smart search component instead of Sebblod's search lists. My thinking simply came from the abandonment of the com_search component on Joomla 5. But as this extension is not linked to Seblod, this does not pose a problem.
Thank you for your reply,
Sebastien
