### ISSUE TITLE
Seblod and Problems with pagination on 5.1.3 & 5.1.4

### ISSUE THREAD

**Issue by denysdesign** [Octopoos/SEBLOD#823]
Hi, guys!
We have more problems with pagination in Seblod list.

Read more:
https://forum.joomla.org/viewtopic.php?t=1011666

**Comment by sebastienheraud** [comment]
Hi Denys,

Yes indeed and we should be able to have a look by the end of the week.

Saba

**Comment by salahjaafar** [comment]
Hello Team,

After updating to Joomla CMS 5.14 and SEBLOD 4.4.0, we've encountered an issue where the Pagination class removes query parameters. If your extension requires additional parameters, they now need to be registered using the "setAdditionalUrlParam" method. You can refer to the Archive view in com_content for an example:
[setAdditionalUrlParam Example](https://github.com/joomla/joomla-cms/blob/51032f65eb10bb9a78be7c264b511a933740318e/components/com_content/src/View/Archive/HtmlView.php#L220)

This change is also causing problems with the table-style search functionality, which is no longer working properly due to missing parameters in the URL.

Thank you for your assistance in resolving this issue.

Best regards,
Salah JAAFAR

**Comment by sebastienheraud** [comment]
Hi,
Fixed included in SEBLOD 4.4.1 for Joomla! 5.1.4
https://www.seblod.com/changelogs#SEBLOD_441_20240919
Saba

**Comment by denysdesign** [comment]
Thank you 👍

**Comment by salahjaafar** [comment]
Congratulation

**Comment by denysdesign** [comment]
> Hi, Fixed included in SEBLOD 4.4.1 for Joomla! 5.1.4 https://www.seblod.com/changelogs#SEBLOD_441_20240919 Saba

Sorry, but it's not work.

So, I'm found mistake.

In file: components/com_cck/views/list/tmpl/default_list.php
string 22

replace:
`if ( strpos( $url, '=&' ) !== false ) {`

to:
`if ( strpos( $url, '&' ) !== false ) {`

And, so, work perfectly!!!
